# Generated by Django 4.0.3 on 2022-11-28 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('pre_nom', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=20)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sceance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=30)),
                ('cours', models.CharField(max_length=30)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_presence.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='SceanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sceance', models.DateField(auto_now_add=True)),
                ('sceance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_presence.sceance')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(max_length=30)),
                ('post_nom', models.CharField(max_length=30)),
                ('pre_nom', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=20)),
                ('presences', models.ManyToManyField(blank=True, related_name='presences', to='gestion_presence.sceanceday')),
                ('sceance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_presence.sceance')),
            ],
        ),
    ]
